HomeWork62/HomeWork62/Models/Cafe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace HomeWork62.Models
{
    public class Cafe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageCafe { get; set; }

        public int BasketId { get; set; }
        public Basket Basket { get; set; }

        public IEnumerable<Dish> Dishes { get; set; }
    }
}

HomeWork62/HomeWork62/Models/CafeViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HomeWork62.Models
{
    public class CafeViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public IFormFile ImageCafe { get; set; }
    }
}

HomeWork62/HomeWork62/Controllers/CafeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HomeWork62.Data;
using HomeWork62.Models;
using HomeWork62.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HomeWork62.Controllers
{
    
    public class CafeController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _environment;
        private readonly FileUploadService _fileUploadService;

        public CafeController(ApplicationDbContext context, IHostingEnvironment environment, FileUploadService fileUploadService)
        {
            _context = context;
            _environment = environment;
            _fileUploadService = fileUploadService;
        }

        // GET: Cafe
        public ActionResult Index()
        {
            var cafes = _context.Cafe;
            return View(cafes);
        }

        // GET: Cafe/Details/5
        public ActionResult Details(int id)
        {
            //Model.Basket.DishInBaskets
            var cafe = _context.Cafe.Include(x => x.Dishes).Include(x => x.Basket).ThenInclude(x => x.DishInBaskets).FirstOrDefault(x => x.Id == id);
            var DishInBasketInCurrentCafe = _context.DishInBasket.Where(x => x.BasketId == cafe.BasketId);
            foreach (var item in DishInBasketInCurrentCafe)
            {
                item.SumDishInBasket = item.CountDish * item.Dish.Price;
                cafe.Basket.Total += item.SumDishInBasket;
            }
            return View(cafe);
        }

        // GET: Cafe/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cafe/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePost(CafeViewModel cafeViewModel)
        {
            //try
            //{
                Cafe cafe = new Cafe {Name = cafeViewModel.Name, ImageCafe = cafeViewModel.ImageCafe.FileName, Description = cafeViewModel.Description };

                var path = Path.Combine(
                   _environment.WebRootPath,
                   $"images\\{cafeViewModel.Name}\\image");
                _fileUploadService.Upload(path, cafeViewModel.ImageCafe.FileName, cafeViewModel.ImageCafe);
                cafe.ImageCafe = $"images/{cafeViewModel.Name}/image/{cafeViewModel.ImageCafe.FileName}";

                _context.Cafe.Add(cafe);
                _context.SaveChanges();

                Basket basket = new Basket { CafeId = cafe.Id, Cafe = cafe};

                _context.Baskets.Add(basket);
                _context.SaveChanges();

                cafe.BasketId = basket.Id;
                cafe.Basket = basket;
                _context.Update(cafe);
                _context.SaveChanges();

            return RedirectToAction(nameof(Index));
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: Cafe/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Cafe/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Cafe/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Cafe/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HomeWork62/HomeWork62/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeWork62.Data;
using HomeWork62.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace HomeWork62.Controllers
{
    public class DishController : Controller
    {
        private readonly ApplicationDbContext _context;
        

        public DishController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dish
        public ActionResult Index()
        {
            return View();
        }

        // GET: Dish/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Dish/Create
        public ActionResult Create(int id)
        {
            ViewBag.CafeId = id;
            ViewBag.CafeName = _context.Cafe.FirstOrDefault(x => x.Id == id).Name;
            return View();
        }

        // POST: Dish/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DishViewModel dishViewModel)
        {
            //try
            //{
            int i = Guid.NewGuid().GetHashCode();

            int j = BitConverter.ToInt32(Guid.NewGuid().ToByteArray(), 0);
            Cafe cafe = _context.Cafe.FirstOrDefault(x => x.Id == dishViewModel.CafeId);
            Dish dish = new Dish {/*Id = i,*/ Name = dishViewModel.Name, Description = dishViewModel.Description, Price = dishViewModel.Price, CafeId = dishViewModel.CafeId, Cafe = cafe};
                

                _context.Dishes.Add(dish);
                _context.SaveChanges();

                return RedirectToAction("Details", "Cafe", new { @id = dish.CafeId });
                //return RedirectToAction(nameof(Index));
            //}
            //catch
            //{
            //    return View();
            //}
        }

        // GET: Dish/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Dish/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Dish/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Dish/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HomeWork62/HomeWork62/Controllers/DishInBasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeWork62.Data;
using HomeWork62.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HomeWork62.Controllers
{
    public class DishInBasketController : Controller
    {
        private readonly ApplicationDbContext _context;


        public DishInBasketController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: DishInBasket
        public ActionResult Index()
        {
            return View();
        }

        // GET: DishInBasket/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Remove(int dishId, int basketId)
        {
            var CafeId = _context.Cafe.FirstOrDefault(x => x.BasketId == basketId).Id;

            var Exist = _context.DishInBasket.Any(x => x.DishId == dishId);

            if (!Exist)
            {
                return RedirectToAction("Details", "Cafe", new { @id = CafeId });
            }

            DishInBasket dishInBasket = _context.DishInBasket.FirstOrDefault( x => x.DishId == dishId);
            dishInBasket.CountDish -= 1;
            if (dishInBasket.CountDish == 0)
            {
                _context.Remove(dishInBasket);
            }
            else
            {
                _context.Update(dishInBasket);
               
            }
            _context.SaveChanges();

            return RedirectToAction("Details", "Cafe", new { @id = CafeId });
        }



            // GET: DishInBasket/Create
            public ActionResult Create(int dishId, int basketId)
        {
            var CafeId = _context.Cafe.FirstOrDefault(x => x.BasketId == basketId).Id;

            var exist = _context.DishInBasket.Any(x => x.DishId == dishId);
            if (exist)
            {
                var dishinbasket = _context.DishInBasket.Include(x => x.Dish).FirstOrDefault(x => x.DishId == dishId);
                dishinbasket.CountDish += 1;
                dishinbasket.SumDishInBasket = dishinbasket.CountDish * dishinbasket.Dish.Price;
                _context.Update(dishinbasket);
                _context.SaveChanges();
            }
            else
            {
                var dish = _context.Dishes.FirstOrDefault(x => x.Id == dishId);
                var basket = _context.Baskets.FirstOrDefault(x => x.Id == basketId);
                DishInBasket dishInBasket = new DishInBasket { DishId = dishId, BasketId = basketId, Dish = dish, Basket = basket, CountDish = 1 };
                dishInBasket.SumDishInBasket = dishInBasket.CountDish * dishInBasket.Dish.Price;
                _context.DishInBasket.Add(dishInBasket);
                _context.SaveChanges();
                
            }

            return RedirectToAction("Details", "Cafe", new { @id = CafeId });
        }

        // POST: DishInBasket/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DishInBasket/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DishInBasket/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: DishInBasket/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DishInBasket/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HomeWork62/HomeWork62/Views/Cafe/Create.cshtml
@model HomeWork62.Models.CafeViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Cafe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <lable asp-for="ImageCafe"></lable><br />
                <input class="form-control" type="file" name="ImageCafe" accept="image/*" />
            </div>
            <div class="form-group">
                <input type="submit" asp-action="CreatePost" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HomeWork62/HomeWork62/Views/Cafe/Details.cshtml
@model HomeWork62.Models.Cafe

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<a asp-action="Index">Back to List Cafe</a>
<h2>Details</h2>

<div>
    <h4>Cafe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ImageCafe)
        </dt>
        <dd>
            <div class="form-group">
                <img src="~/@Model.ImageCafe" width="100" height="100" />
            </div>
        </dd>
    </dl>
</div>
<div class="BasketBlock">
    <h2>Basket</h2>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Count</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Basket.DishInBaskets)
            {
                <tr>
                    <td>@item.Dish.Name</td>
                    <td>@item.SumDishInBasket</td>
                    <td>@item.CountDish</td>
                </tr>
            }
        </tbody>

    </table>
    <p>Total: @Model.Basket.Total</p>
</div>
<hr />
<div>
    <a asp-action="Create" asp-controller="Dish" asp-route-id="@Model.Id">Create New Dish</a>
</div>
<h2>Dishes</h2>

@{ int count = Model.Dishes.Count();}
@if (count != 0)
{
    <div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Price
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Dishes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)
                        </td>
                        <td>
                            <a asp-action="Create" asp-controller="DishInBasket" asp-route-dishId="@item.Id" asp-route-basketId="@Model.BasketId">Add portion In Basket</a> |
                            <a asp-action="Remove" asp-controller="DishInBasket" asp-route-dishId="@item.Id" asp-route-basketId="@Model.BasketId">Remove portion In Basket</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <div>
        Нету блюд
    </div>

}

HomeWork62/HomeWork62/Views/Cafe/Index.cshtml
@model IEnumerable<HomeWork62.Models.Cafe>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cafe list</h2>

<p>
    <a asp-action="Create">Create New Cafe</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageCafe)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Cafe" asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <img src="~/@item.ImageCafe" width="100" height="100" />
                </td>
                
            </tr>
        }
    </tbody>
</table>